### ISSUE TITLE
Issue Tracker

### ISSUE THREAD

**Issue by BobAubouin** [BobAubouin/Python_Anesthesia_Simulator#19]
This issue is intended to track possible contribution to enhance the simulator. Any help from the community will be valuable.

Here is the list:
- [ ] Add new drugs to the simulator (Dopamine, Epinephrine, Ketamine)
- [ ] Implement neuromuscular system (input and output)
- [ ] Add a more physiological model for hemodynamic
- [ ] Consider the effect of drugs on the respiratory system
- [ ] Implement new shock scenario to test the controllers on divers scenarios
